{% set name = "pycmtensor" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycmtensor-{{ version }}.tar.gz
  sha256: c19ed676ce18a741e518c280db68051bc1a24cd6209ef70885d21d83fea7a6c5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.11.0,<4.0.0
    - aesara 2.9.3
    - numpy 1.25.2
    - scipy 1.11.4
    - pandas 1.5.3
    - seaborn 0.12.2
    - watermark 2.4.3

test:
  imports:
    - pycmtensor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mwong009/pycmtensor
  summary: A robust and efficient Python package leveraging tensor computations for advanced discrete choice modelling.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mwong009
