{% set python_min = "3.11.0" %}
{% set name = "pycmtensor" %}
{% set version = "1.14.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycmtensor-{{ version }}.tar.gz
  sha256: 90b3e3b868e517cb17a9816721d7f4f2b316f5b5238efc3146d976dc57ff26e6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - aesara 2.9.3
    - numpy 1.25.2
    - scipy 1.11.4
    - pandas 1.5.3
    - seaborn 0.12.2
    - watermark 2.4.3
    - scikit-learn 1.5.2

test:
  imports:
    - pycmtensor
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mwong009/pycmtensor
  summary: A robust and efficient Python package leveraging tensor computations for advanced discrete choice modelling.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mwong009
